name: event_master
description: "Event management application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-97.0.dev

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  bloc: ^8.1.3
  # Network & API
  dio: ^5.4.1
  json_annotation: ^4.8.1
  # UI components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  # Storage
  shared_preferences: ^2.2.2
  # Utils
  logger: ^2.0.2+1
  uuid: ^4.3.3
  url_launcher: ^6.2.5
  # Dependency injection
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  bloc_test: ^9.1.6
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
