openapi: 3.0.3
info:
  title: HTech Event Management API
  version: 1.0.0
  description: |
    # Event Management API
    
    This API provides a comprehensive set of endpoints for managing events, participants, categories, and tags.
    
    ## Key Features
    
    * **User authentication** - Register, login, and manage user accounts
    * **Event management** - Create, update, delete, and search events
    * **Category organization** - Organize events by categories
    * **Tagging system** - Add multiple tags to events for better searchability
    * **Participant management** - Register for events and track attendance
    
    ## Authentication
    
    All protected endpoints require a valid JWT token, which can be obtained from the /auth/login endpoint.
    Include the token in the Authorization header as a Bearer token.
    
    ## Pagination
    
    List endpoints support pagination through the `page` and `size` query parameters, and sorting through
    the `sortBy` and `sortOrder` parameters.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: API Support
    email: support@htechevents.com
    url: https://htechevents.com/support

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.htechevents.com
    description: Production server

tags:
  - name: Auth
    description: Authentication and authorization operations
  - name: Users
    description: User account management
  - name: Admin
    description: Administrative operations for user management
  - name: Events
    description: Create, read, update, and delete events
  - name: Categories
    description: Manage event categories for organization
  - name: Participants
    description: Register for events and manage participation
  - name: Tags
    description: Create and manage tags for events

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from the authentication endpoint